=== mikld86/GMTiredandForked/schema/profile.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Espresso Profile Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid"
    },
    "label": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "enum": [
        "standard",
        "pro"
      ]
    },
    "description": {
      "type": "string"
    },
    "temperature": {
      "type": "number"
    },
    "favorite": {
      "type": "boolean"
    },
    "selected": {
      "type": "boolean"
    },
    "phases": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string"
          },
          "phase": {
            "type": "string",
            "enum": [
              "preinfusion",
              "brew"
            ]
          },
          "valve": {
            "type": "integer",
            "enum": [
              0,
              1
            ]
          },
          "duration": {
            "type": "number",
            "minimum": 0
          },
          "pump": {
            "oneOf": [
              {
                "type": "number",
                "enum": [
                  0,
                  1
                ]
              },
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "target": {
                    "type": "string",
                    "enum": [
                      "pressure",
                      "flow"
                    ]
                  },
                  "pressure": {
                    "type": "number",
                    "minimum": 0
                  },
                  "flow": {
                    "type": "number",
                    "minimum": 0
                  }
                },
                "required": [
                  "target",
                  "pressure",
                  "flow"
                ]
              }
            ]
          },
          "targets": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "type": {
                  "type": "string",
                  "enum": [
                    "volumetric",
                    "pressure"
                  ]
                },
                "value": {
                  "type": "number",
                  "minimum": 0
                }
              },
              "required": [
                "type",
                "value"
              ]
            }
          }
        },
        "required": [
          "name",
          "phase",
          "valve",
          "duration",
          "pump"
        ]
      }
    }
  },
  "required": [
    "id",
    "label",
    "type",
    "description",
    "phases"
  ]
}

=== mikld86/GMTiredandForked/web/src/mocks/profiles.json
[
  {
    "id": "b1f86708-9161-4b87-a7b2-3cedb9d7c244",
    "label": "GaggiMate Classic",
    "type": "standard",
    "favorite": false,
    "description": "Standard profile with pre-infusion phase",
    "phases": [
      {
        "name": "Pump",
        "phase": "preinfusion",
        "valve": 1,
        "pump": 1,
        "duration": 3
      },
      {
        "name": "Bloom",
        "phase": "preinfusion",
        "valve": 1,
        "pump": 0,
        "duration": 5
      },
      {
        "name": "Pump",
        "phase": "brew",
        "valve": 1,
        "pump": 1,
        "duration": 50,
        "targets": [
          {
            "type": "volumetric",
            "value": 36
          }
        ]
      }
    ]
  },
  {
    "id": "a81d74c6-58a8-4140-9c4d-07c9b377913c",
    "label": "LM Leva",
    "type": "pro",
    "selected": true,
    "favorite": true,
    "description": "Ramps up pressure and flow to achieve similar results to a lever operated machine.",
    "phases": [
      {
        "name": "Preinfusion Low",
        "phase": "preinfusion",
        "valve": 1,
        "pump": {
          "target": "pressure",
          "pressure": 4,
          "flow": 2
        },
        "duration": 3,
        "targets": [
          {
            "type": "pressure",
            "value": 4.5
          }
        ]
      },
      {
        "name": "Preinfusion Bloom",
        "phase": "preinfusion",
        "valve": 1,
        "pump": {
          "target": "pressure",
          "pressure": 1,
          "flow": 1
        },
        "duration": 5
      },
      {
        "name": "Ramp Up",
        "phase": "brew",
        "valve": 1,
        "pump": {
          "target": "pressure",
          "pressure": 8,
          "flow": 2
        },
        "duration": 3,
        "targets": [
          {
            "type": "pressure",
            "value": 8
          }
        ]
      },
      {
        "name": "Hold",
        "phase": "brew",
        "valve": 1,
        "pump": {
          "target": "pressure",
          "pressure": 8,
          "flow": 1.5
        },
        "duration": 20,
        "targets": [
          {
            "type": "volumetric",
            "value": 36
          }
        ]
      }
    ]
  },
  {
    "id": "d7295f5e-3e53-4949-bc7f-26885c6fd164",
    "label": "LM Leva 2",
    "type": "pro",
    "favorite": true,
    "description": "Ramps up pressure and flow to achieve similar results to a lever operated machine.",
    "phases": [
      {
        "name": "Preinfusion Low",
        "phase": "preinfusion",
        "valve": 1,
        "pump": {
          "target": "pressure",
          "pressure": 4,
          "flow": 2
        },
        "duration": 3,
        "targets": [
          {
            "type": "pressure",
            "value": 4.5
          }
        ]
      },
      {
        "name": "Preinfusion Bloom",
        "phase": "preinfusion",
        "valve": 1,
        "pump": {
          "target": "pressure",
          "pressure": 1,
          "flow": 1
        },
        "duration": 5
      },
      {
        "name": "Ramp Up",
        "phase": "brew",
        "valve": 1,
        "pump": {
          "target": "pressure",
          "pressure": 8,
          "flow": 2
        },
        "duration": 3,
        "targets": [
          {
            "type": "pressure",
            "value": 8
          }
        ]
      },
      {
        "name": "Hold",
        "phase": "brew",
        "valve": 1,
        "pump": {
          "target": "flow",
          "pressure": 8,
          "flow": 1.5
        },
        "duration": 20,
        "targets": [
          {
            "type": "volumetric",
            "value": 36
          }
        ]
      }
    ]
  },
  {
    "id": "2a31aa27-1d72-4b14-9f90-8fb050ea033d",
    "label": "LM Leva 3",
    "type": "pro",
    "description": "Ramps up pressure and flow to achieve similar results to a lever operated machine.",
    "phases": [
      {
        "name": "Preinfusion Low",
        "phase": "preinfusion",
        "valve": 1,
        "pump": {
          "target": "pressure",
          "pressure": 4,
          "flow": 2
        },
        "duration": 3,
        "targets": [
          {
            "type": "pressure",
            "value": 4.5
          }
        ]
      },
      {
        "name": "Preinfusion Bloom",
        "phase": "preinfusion",
        "valve": 1,
        "pump": {
          "target": "pressure",
          "pressure": 1,
          "flow": 1
        },
        "duration": 5
      },
      {
        "name": "Ramp Up",
        "phase": "brew",
        "valve": 1,
        "pump": {
          "target": "pressure",
          "pressure": 8,
          "flow": 2
        },
        "duration": 3,
        "targets": [
          {
            "type": "pressure",
            "value": 8
          }
        ]
      },
      {
        "name": "Hold",
        "phase": "brew",
        "valve": 1,
        "pump": {
          "target": "flow",
          "pressure": 9,
          "flow": 1.5
        },
        "duration": 20,
        "targets": [
          {
            "type": "volumetric",
            "value": 36
          }
        ]
      }
    ]
  }
]
